'use client';
import { useState } from 'react';
import Image from 'next/image';
import Link from 'next/link';
import { Icon, Modal } from '@/components/ui';
import { SCREENS, GROUPS } from '@/lib/screens';
import DashboardV2 from './DashboardV2';
import { DashboardPreferences, QuickCreate, useDashboardPreferences } from './Preferences';

const groupNames: Record<string, string> = { overview: 'نظرة عامة', procurement: 'المشتريات', revenue: 'الإيرادات', fleet: 'الأسطول', sivamar_qb: 'المحاسبة', admin: 'الإدارة' };
function PreviewShell() {
  const { collapsed, setCollapsed } = useDashboardPreferences();
  const [mobile, setMobile] = useState(false);
  const [info, setInfo] = useState(false);
  const nav = <><div className="flex h-20 items-center gap-3 border-b border-white/10 px-5"><Image src={collapsed ? '/ume-mark-light.svg' : '/ume-logo-light.svg'} alt="UME" width={collapsed ? 32 : 108} height={32} />{!collapsed && <span className="text-xs text-slate-400">PMS</span>}</div><nav className="min-h-0 flex-1 overflow-y-auto px-3 py-4">{GROUPS.filter(g => g.key !== 'sivamar_qb' && g.key !== 'admin').map(g => <div key={g.key} className="mb-5">{!collapsed && <div className="mb-2 flex items-center gap-3 px-2 text-[11px] text-[#84a3ad]">{groupNames[g.key]}<span className="h-px flex-1 bg-white/10" /></div>}{SCREENS.filter(item => item.group === g.key && !item.hidden).map(item => <Link key={item.href} prefetch={false} href={item.href === '/dashboard' ? '/preview/dashboard' : item.href} title={item.label} aria-current={item.href === '/dashboard' ? 'page' : undefined} className={'mb-1 flex items-center gap-3 rounded-lg px-3 py-3 text-[13px] ' + (item.href === '/dashboard' ? 'bg-[#123f48] text-white' : 'text-[#b2c6ce] hover:bg-white/5')}><Icon name={item.iconName || 'file'} size={19} />{!collapsed && <span>{item.label}</span>}</Link>)}</div>)}</nav><button className="flex items-center justify-center gap-3 border-t border-white/10 p-4 text-sm text-[#b2c6ce]" onClick={() => setCollapsed(!collapsed)} aria-label={collapsed ? 'توسيع القائمة' : 'طي القائمة'}><Icon name={collapsed ? 'chevronLeft' : 'chevronRight'} size={17} />{!collapsed && 'طي القائمة'}</button></>;
  return <div dir="rtl" className="flex h-dvh overflow-hidden bg-[#f5f7f9]"><aside className={'hidden shrink-0 flex-col bg-[#00283a] text-white transition-[width] md:flex ' + (collapsed ? 'w-[76px]' : 'w-[236px]')}>{nav}</aside>{mobile && <div className="fixed inset-0 z-40 bg-black/40 md:hidden" onClick={() => setMobile(false)}><aside className="absolute inset-y-0 right-0 flex w-[250px] flex-col bg-[#00283a] text-white" onClick={e => e.stopPropagation()}><button aria-label="إغلاق القائمة" className="absolute left-2 top-3 p-2" onClick={() => setMobile(false)}><Icon name="x" /></button>{nav}</aside></div>}<div className="flex min-w-0 flex-1 flex-col"><header className="flex h-20 shrink-0 items-center gap-4 border-b bg-white px-4 md:px-7"><button className="md:hidden" aria-label="فتح القائمة" onClick={() => setMobile(true)}><Icon name="menu" /></button><span className="text-sm font-semibold text-[#00283a]">الرئيسية</span><span className="hidden text-xs text-slate-400 sm:block">/ نظرة عامة</span><div className="mr-auto flex items-center gap-3"><QuickCreate /><button title="الإنجليزية غير متاحة في هذه النسخة" disabled className="text-xs text-slate-400">EN</button><button onClick={() => setInfo(true)} className="rounded-lg p-2 text-slate-500 hover:bg-slate-50" aria-label="معلومات المعاينة"><Icon name="info" size={20} /></button><div className="flex items-center gap-2 border-r pr-3"><span className="flex h-9 w-9 items-center justify-center rounded-full bg-[#3d8a67] text-sm text-white">مح</span><span className="hidden text-xs leading-5 text-[#526777] lg:block">محمد السيد<br /><small className="text-slate-400">معاينة التصميم</small></span></div></div></header><main className="min-h-0 flex-1 overflow-auto p-4 md:p-6"><DashboardV2 /></main></div><Modal open={info} onClose={() => setInfo(false)} title="معاينة UME Dashboard v2"><p className="text-sm leading-8 text-slate-600">هذه معاينة منفصلة ببيانات تجريبية، ولا تتصل ببيانات النظام أو تغيّر صلاحياته. روابط الأقسام تفتح صفحات المشروع التي تتطلب تسجيل الدخول. المسودات والمراجعات مؤقتة لهذه الجلسة.</p></Modal></div>;
}
export default function DashboardPreview() { return <DashboardPreferences><PreviewShell /></DashboardPreferences>; }
