/*
 * نصوص كشف حساب المورّد — منقولةٌ من تسليم التصميم v1.2 (`TX`)، بعد حذف
 * نصوص نموذج المراجعة وحده (بيانات تجريبيّة · CSV تجريبيّ · محاكاة الأدوار).
 */
import type { ExportLabels, TxKind } from './statement';

export const STX = {
  ar: {
    filters: 'الفلاتر', suppliers: 'الموردون', selected: 'مختار', supSearch: 'ابحث عن مورد…', selectShown: 'تحديد الظاهر', clearAll: 'إلغاء الكل',
    noSup: 'لا يوجد مورد بهذا الاسم', supLoading: 'جارٍ تحميل الموردين…', currency: 'العملة', all: 'الكل',
    dateNote: 'مصدر هذا التقرير لا يدعم نطاق تاريخ؛ يُعرض السجل الكامل لكل مورد وعملة.',
    run: 'عرض التقرير', reset: 'إعادة الضبط', running: 'جارٍ التحميل…', needSup: 'اختر مورداً واحداً على الأقل.',
    cancelled: 'أُلغي الطلب السابق لأن الاختيارات تغيّرت.', dirty: 'غيّرت الاختيارات. النتائج المعروضة ما زالت للاختيارات السابقة.', notApplied: 'غير مطبّق',
    appliedTitle: 'النتائج معروضة لـ', initialTitle: 'اختر مورداً أو أكثر ثم اضغط «عرض التقرير»', initialBody: 'لكل مورد دفتر مستقل لكل عملة: مدين، دائن، ورصيد متراكم.',
    errTitle: 'تعذّر تحميل الكشف', errBody: 'تحقق من الاتصال ثم أعد المحاولة.', retry: 'إعادة المحاولة', stale: 'فشل التحديث. المعروض هو آخر نتائج ناجحة ولم يُحدَّث.',
    noAccess: 'لا تملك صلاحية كشف حساب الموردين. لم يُرسَل أي طلب.',
    sumTitle: 'ملخص حسب العملة', sumNote: 'كل عملة دفتر مستقل. لا يوجد إجمالي موحّد ولا تحويل بين العملات.',
    opening: 'رصيد افتتاحي', invoices: 'فواتير', payments: 'سدادات', credits: 'إشعارات دائنة', closing: 'الرصيد الختامي',
    txSearch: 'بحث في الحركات: البيان، السفينة، المرجع', order: 'ترتيب العرض', orderAsc: 'الأقدم أولاً', orderDesc: 'الأحدث أولاً', orderLbl: 'الترتيب',
    colDate: 'التاريخ', colType: 'النوع', colDesc: 'البيان', colVessel: 'السفينة', colDebit: 'مدين', colCredit: 'دائن', colBalance: 'الرصيد', colRef: 'المرجع',
    kInvoice: 'فاتورة', kPayment: 'سداد', kCredit: 'إشعار دائن', kLegacy: 'تسوية تاريخية', kUnevidenced: 'إغلاق بلا سند', prev: 'السابق', next: 'التالي', pageSize: 'حجم الصفحة',
    noTx: 'لا توجد حركات لهذا المورد', noMatch: 'لا حركات مطابقة للبحث في هذا الدفتر', noCcyTx: 'للمورد حركات بعملات أخرى فقط.', showAllCcy: 'عرض كل العملات',
    noCcyAny: (c: string) => `لا يملك أيٌّ من الموردين المختارين حركات بعملة ${c}.`,
    openingNA: 'غير متاح', openingNANote: 'بعض الدفاتر بلا رصيد افتتاحي من المصدر؛ استُبعدت من الرصيد الختامي، ويظهر صافي حركاتها منفصلاً تحته.',
    netBanner: 'الرصيد الافتتاحي غير متاح من المصدر لهذا الدفتر. عمود «صافي تراكمي» يبدأ من صفر ويمثّل صافي الحركات فقط، وليس رصيد الحساب.',
    netClosing: 'صافي الحركات — الافتتاحي غير متاح', netHead: 'صافي تراكمي', basisCol: 'أساس الرصيد', basisFull: 'رصيد كامل', basisNet: 'صافي الحركات — الافتتاحي غير متاح',
    knownOnly: (n: number) => `المعروف فقط · ${n} دفتر ناقص`, excludes: (n: number) => `لا يشمل ${n} دفتر بلا افتتاحي · صافي حركاتها: `,
    exportTitle: 'التصدير والطباعة', exportXlsx: 'تصدير Excel', exportLedger: 'Excel لهذا الدفتر', print: 'طباعة / حفظ PDF', printNow: 'طباعة أو حفظ PDF', close: 'إغلاق',
    copyLink: 'نسخ رابط التقرير', linkCopied: 'نُسخ الرابط',
    linkNote: 'الرابط يحفظ: التقرير والموردين والعملة. لا يحفظ: بحث الجدول والترتيب وحجم الصفحة. فتحه يتطلب تسجيل الدخول والصلاحية.',
    printFoot: 'الأرصدة كما في السجل الكامل لكل مورد وعملة؛ لا تحويل بين العملات.',
    details: 'تفاصيل', amount: 'المبلغ', balAfter: 'الرصيد بعد الحركة',
    savedSets: 'مجموعات الفلاتر المحفوظة', savedSetsNote: 'تُحفظ الاختيارات فقط دون النتائج، ويُعاد التحقق من صلاحيات الموردين عند الاستعادة.',
    saveSet: 'حفظ الاختيارات الحالية باسم', setNameLabel: 'اسم المجموعة', setNamePh: 'مثال: موردو الوقود — دولار', save: 'حفظ', cancel: 'إلغاء', setNameReq: 'اكتب اسماً للمجموعة.',
    setSaved: 'حُفظت المجموعة', setSavedSub: 'حُفظ الموردون والعملة فقط، لحسابك على هذا المتصفح.', setRestored: 'استُعيدت المجموعة', setRestoredSub: 'اضغط «عرض التقرير» لتطبيقها.',
    setDropped: (n: number) => `استُبعد ${n} مورد لم يعد ضمن صلاحياتك`, setDroppedSub: 'استُعيد الباقي. اضغط «عرض التقرير» لتطبيقه.',
    linkDropped: (n: number) => `استُبعد ${n} مورد من الرابط`, linkDroppedSub: 'غير موجود أو خارج صلاحياتك.',
    restore: 'استعادة المجموعة ', del: 'حذف المجموعة ',
    jumpTitle: 'انتقال سريع إلى دفتر', clearTxq: 'مسح بحث الحركات', clear: 'مسح', fullLedger: 'السجل الكامل',
    totPage: (n: number) => `هذه الصفحة (${n})`, totMatch: (n: number) => `المطابق للبحث (${n})`, totFull: (n: number) => `السجل الكامل (${n})`,
    txMatch: (m: number, n: number) => `${m} حركة مطابقة من ${n}. الرصيد في كل سطر هو رصيده في السجل الكامل.`,
    balNote: 'الرصيد في كل سطر هو الرصيد المتراكم من السجل الكامل، ولا يعيد البحث أو الترتيب حسابه.',
    completeness: 'حالة الأرصدة', complete: 'مكتملة', incomplete: (n: number) => `ناقصة: ${n} دفتر بلا رصيد افتتاحي`,
    report: 'التقرير', extracted: 'تاريخ الاستخراج', search: 'بحث الجدول', rowsN: 'عدد الحركات',
    ledgers: (n: number) => `${n} دفتر`, supCount: (n: number) => `${n} مورد`, page: (p: number, n: number) => `صفحة ${p} من ${n}`,
    exportScope: (n: number, ord: string, q: boolean) => `يشمل التصدير والطباعة كل الحركات المطابقة للفلاتر المطبّقة${q ? ' وبحث الجدول' : ''}: ${n} حركة من كل الصفحات، وبنفس ترتيب العرض (${ord})، مع عمودَي «المرجع» و«أساس الرصيد».`,
    extractedAt: 'استُخرج ', reportTitle: 'كشف حساب مورد', collapse: 'طيّ الفلاتر', expand: 'عرض الفلاتر',
  },
  en: {
    filters: 'Filters', suppliers: 'Suppliers', selected: 'selected', supSearch: 'Search suppliers…', selectShown: 'Select shown', clearAll: 'Clear all',
    noSup: 'No supplier matches', supLoading: 'Loading suppliers…', currency: 'Currency', all: 'All',
    dateNote: 'This report’s source has no date range; the full ledger per supplier and currency is shown.',
    run: 'Run report', reset: 'Reset', running: 'Loading…', needSup: 'Select at least one supplier.',
    cancelled: 'Previous request cancelled because selections changed.', dirty: 'Selections changed. Results still reflect the previous selection.', notApplied: 'not applied',
    appliedTitle: 'Showing results for', initialTitle: 'Pick one or more suppliers, then Run report', initialBody: 'Each supplier gets a separate ledger per currency: debit, credit, running balance.',
    errTitle: 'Couldn’t load the statement', errBody: 'Check your connection and try again.', retry: 'Retry', stale: 'Refresh failed. Showing the last successful results (not updated).',
    noAccess: 'You don’t have access to supplier statements. No request was sent.',
    sumTitle: 'Summary by currency', sumNote: 'Each currency is a separate ledger. No combined total, no conversion.',
    opening: 'Opening', invoices: 'Invoices', payments: 'Payments', credits: 'Credit notes', closing: 'Closing',
    txSearch: 'Search transactions: description, vessel, ref', order: 'Order', orderAsc: 'Oldest first', orderDesc: 'Newest first', orderLbl: 'Order',
    colDate: 'Date', colType: 'Type', colDesc: 'Description', colVessel: 'Vessel', colDebit: 'Debit', colCredit: 'Credit', colBalance: 'Balance', colRef: 'Reference',
    kInvoice: 'Invoice', kPayment: 'Payment', kCredit: 'Credit note', kLegacy: 'Historical settlement', kUnevidenced: 'Closed without voucher', prev: 'Previous', next: 'Next', pageSize: 'Page size',
    noTx: 'No transactions for this supplier', noMatch: 'No rows match the search in this ledger', noCcyTx: 'This supplier only has transactions in other currencies.', showAllCcy: 'Show all currencies',
    noCcyAny: (c: string) => `None of the selected suppliers has transactions in ${c}.`,
    openingNA: 'N/A', openingNANote: 'Some ledgers have no opening balance from the source; they are excluded from the closing balance and their net movement is shown separately below it.',
    netBanner: 'The source provides no opening balance for this ledger. “Running net” starts at zero and shows net movements only, not the account balance.',
    netClosing: 'Net movement — opening not available', netHead: 'Running net', basisCol: 'Balance basis', basisFull: 'Full balance', basisNet: 'Net movement — opening not available',
    knownOnly: (n: number) => `known only · ${n} ledger(s) missing`, excludes: (n: number) => `Excludes ${n} ledger(s) without opening · their net movement: `,
    exportTitle: 'Export & print', exportXlsx: 'Export Excel', exportLedger: 'Excel for this ledger', print: 'Print / Save PDF', printNow: 'Print or save PDF', close: 'Close',
    copyLink: 'Copy report link', linkCopied: 'Link copied',
    linkNote: 'The link keeps: report, suppliers, currency. It doesn’t keep: table search, order, page size. Opening it requires sign-in and access.',
    printFoot: 'Balances are as in each full ledger; no currency conversion.',
    details: 'Details', amount: 'Amount', balAfter: 'Balance after',
    savedSets: 'Saved filter sets', savedSetsNote: 'Only selections are saved, never results. Supplier access is re-checked on restore.',
    saveSet: 'Save current selection as…', setNameLabel: 'Set name', setNamePh: 'e.g. Bunker suppliers — USD', save: 'Save', cancel: 'Cancel', setNameReq: 'Enter a name for the set.',
    setSaved: 'Set saved', setSavedSub: 'Suppliers and currency only, for your account on this browser.', setRestored: 'Set restored', setRestoredSub: 'Press Run report to apply it.',
    setDropped: (n: number) => `${n} supplier(s) removed — no longer in your access`, setDroppedSub: 'The rest was restored. Press Run report to apply.',
    linkDropped: (n: number) => `${n} supplier(s) removed from the link`, linkDroppedSub: 'Unknown or outside your access.',
    restore: 'Restore set ', del: 'Delete set ',
    jumpTitle: 'Jump to ledger', clearTxq: 'Clear transaction search', clear: 'Clear', fullLedger: 'Full ledger',
    totPage: (n: number) => `This page (${n})`, totMatch: (n: number) => `Matching search (${n})`, totFull: (n: number) => `Full ledger (${n})`,
    txMatch: (m: number, n: number) => `${m} of ${n} transactions match. Each row keeps its full-ledger balance.`,
    balNote: 'Each row’s balance is the running balance from the full ledger; search and order never recompute it.',
    completeness: 'Balance status', complete: 'Complete', incomplete: (n: number) => `Incomplete: ${n} ledger(s) without opening balance`,
    report: 'Report', extracted: 'Extracted', search: 'Table search', rowsN: 'Transactions',
    ledgers: (n: number) => `${n} ledger(s)`, supCount: (n: number) => `${n} supplier(s)`, page: (p: number, n: number) => `Page ${p} of ${n}`,
    exportScope: (n: number, ord: string, q: boolean) => `Export and print include every row matching the applied filters${q ? ' and the table search' : ''}: ${n} rows across all pages, in the on-screen order (${ord}), with “Reference” and “Balance basis” columns.`,
    extractedAt: 'Extracted ', reportTitle: 'Supplier Statement', collapse: 'Collapse filters', expand: 'Show filters',
  },
};
export type StatementText = typeof STX.ar;

export const kindLabel = (T: StatementText, k: TxKind) =>
  k === 'invoice' ? T.kInvoice : k === 'payment' ? T.kPayment : k === 'credit_note' ? T.kCredit
    : k === 'legacy_settlement' ? T.kLegacy : T.kUnevidenced;

export function exportLabels(T: StatementText): ExportLabels {
  return {
    report: T.report, extracted: T.extracted, suppliers: T.suppliers, currency: T.currency, search: T.search, order: T.orderLbl,
    status: T.completeness, rowsN: T.rowsN, complete: T.complete, incomplete: T.incomplete, all: T.all,
    orderAsc: T.orderAsc, orderDesc: T.orderDesc,
    head: [T.suppliers, T.currency, T.colDate, T.colType, T.colRef, T.colDesc, T.colVessel, T.colDebit, T.colCredit, T.colBalance, T.basisCol],
    kind: (k) => kindLabel(T, k), basisFull: T.basisFull, basisNet: T.basisNet,
  };
}
